/**
 * Email Templates for Smart Rental Alert Notifications
 *
 * All templates return plain HTML strings suitable for Resend.
 * They reference no external secrets — just format the data passed to them.
 *
 * Server-side only. Never import this in browser (frontend) code.
 */

export type AlertEmailData = {
  alertTitle: string;
  alertType: string;
  severity: "critical" | "warning" | "info";
  assetId: string;
  signal: string;
  impact: string;
  action: string;
  recipientName: string;
  recipientEmail: string;
  appBaseUrl: string;
};

const SEVERITY_COLORS = {
  critical: "#EF4444",
  warning: "#F59E0B",
  info: "#6B7280",
};

const SEVERITY_LABELS = {
  critical: "🚨 CRITICAL ALERT",
  warning: "⚠️ OPERATIONAL WARNING",
  info: "ℹ️ FLEET NOTICE",
};

/**
 * Generates a rich HTML email for an operational alert.
 * Designed to be readable on both desktop and mobile email clients.
 */
export function buildAlertEmail(data: AlertEmailData): {
  subject: string;
  html: string;
  text: string;
} {
  const color = SEVERITY_COLORS[data.severity];
  const label = SEVERITY_LABELS[data.severity];

  const subject = `${data.severity === "critical" ? "🚨" : "⚠️"} [Smart Rental] ${data.alertTitle}`;

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${subject}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #F5F5F5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
  </style>
</head>
<body style="background:#F5F5F5; padding: 32px 0;">
  <div style="max-width: 560px; margin: 0 auto; background: #FFFFFF; border-radius: 20px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08);">

    <!-- Header -->
    <div style="background: ${color}; padding: 24px 28px;">
      <p style="color: rgba(255,255,255,0.85); font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 6px;">${label}</p>
      <h1 style="color: #FFFFFF; font-size: 18px; font-weight: 800; line-height: 1.3; margin: 0;">${data.alertTitle}</h1>
    </div>

    <!-- Body -->
    <div style="padding: 24px 28px;">
      <p style="color: #6B7280; font-size: 13px; margin-bottom: 20px;">Hello ${data.recipientName},</p>

      <!-- Alert Detail Card -->
      <div style="background: #F9FAFB; border: 1px solid #E5E7EB; border-radius: 12px; padding: 16px; margin-bottom: 20px;">
        <div style="margin-bottom: 12px;">
          <p style="font-size: 10px; font-weight: 700; text-transform: uppercase; color: #9CA3AF; letter-spacing: 0.08em; margin-bottom: 4px;">Asset</p>
          <p style="font-size: 14px; font-weight: 700; color: #111827;">${data.assetId}</p>
        </div>
        <div style="margin-bottom: 12px;">
          <p style="font-size: 10px; font-weight: 700; text-transform: uppercase; color: #9CA3AF; letter-spacing: 0.08em; margin-bottom: 4px;">Signal</p>
          <p style="font-size: 13px; color: #374151;">${data.signal}</p>
        </div>
        <div style="margin-bottom: 12px;">
          <p style="font-size: 10px; font-weight: 700; text-transform: uppercase; color: #9CA3AF; letter-spacing: 0.08em; margin-bottom: 4px;">Business Impact</p>
          <p style="font-size: 13px; color: #374151;">${data.impact}</p>
        </div>
        <div style="background: ${color}15; border-left: 3px solid ${color}; border-radius: 0 8px 8px 0; padding: 10px 12px;">
          <p style="font-size: 10px; font-weight: 700; text-transform: uppercase; color: ${color}; margin-bottom: 3px;">Recommended Action</p>
          <p style="font-size: 13px; font-weight: 600; color: #111827;">${data.action}</p>
        </div>
      </div>

      <!-- CTA Button -->
      <div style="text-align: center; margin-bottom: 24px;">
        <a href="${data.appBaseUrl}/alerts"
           style="display: inline-block; background: #111827; color: #FFFFFF; font-size: 13px; font-weight: 700; padding: 12px 28px; border-radius: 50px; text-decoration: none; letter-spacing: 0.01em;">
          Open Alert Command Center →
        </a>
      </div>

      <!-- Footer Note -->
      <p style="color: #9CA3AF; font-size: 11px; text-align: center; border-top: 1px solid #E5E7EB; padding-top: 16px; line-height: 1.6;">
        This alert was generated by Smart Rental — RentSense Fleet OS.<br />
        You are receiving this because you are listed as a fleet operations contact.<br />
        <a href="${data.appBaseUrl}" style="color: #6B7280;">Open Dashboard</a>
      </p>
    </div>
  </div>
</body>
</html>`.trim();

  // Plain-text fallback for email clients that don't render HTML
  const text = `
${label}
${data.alertTitle}

Hello ${data.recipientName},

Asset: ${data.assetId}
Alert Type: ${data.alertType}

Signal: ${data.signal}

Business Impact: ${data.impact}

Recommended Action: ${data.action}

Open Alert Command Center: ${data.appBaseUrl}/alerts

---
Smart Rental — RentSense Fleet OS
`.trim();

  return { subject, html, text };
}

/**
 * Generates a summary digest email for multiple alerts at once.
 * Used for daily digest or batch notifications.
 */
export function buildAlertDigestEmail(
  alerts: Array<{ title: string; type: string; severity: "critical" | "warning" | "info" }>,
  data: { recipientName: string; recipientEmail: string; appBaseUrl: string },
): { subject: string; html: string; text: string } {
  const criticalCount = alerts.filter((a) => a.severity === "critical").length;
  const warningCount = alerts.filter((a) => a.severity === "warning").length;

  const subject = `[Smart Rental] Fleet Alert Digest — ${criticalCount} Critical, ${warningCount} Warnings`;

  const rowsHtml = alerts
    .map(
      (a) => `
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #F3F4F6;">
          <span style="display: inline-block; background: ${SEVERITY_COLORS[a.severity]}20; color: ${SEVERITY_COLORS[a.severity]}; font-size: 10px; font-weight: 700; padding: 2px 8px; border-radius: 20px;">${a.type}</span>
        </td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #F3F4F6; font-size: 13px; color: #111827;">${a.title}</td>
      </tr>`,
    )
    .join("");

  const html = `
<!DOCTYPE html>
<html lang="en">
<body style="background:#F5F5F5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 32px 0;">
  <div style="max-width: 560px; margin: 0 auto; background: #FFFFFF; border-radius: 20px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08);">
    <div style="background: #111827; padding: 24px 28px;">
      <p style="color: rgba(255,255,255,0.6); font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 6px;">FLEET ALERT DIGEST</p>
      <h1 style="color: #FFFFFF; font-size: 18px; font-weight: 800; margin: 0;">${alerts.length} Active Alerts Require Attention</h1>
    </div>
    <div style="padding: 24px 28px;">
      <p style="color: #6B7280; font-size: 13px; margin-bottom: 20px;">Hello ${data.recipientName}, here is a summary of active fleet alerts:</p>
      <table style="width: 100%; border-collapse: collapse; border: 1px solid #E5E7EB; border-radius: 12px; overflow: hidden;">
        ${rowsHtml}
      </table>
      <div style="text-align: center; margin-top: 24px;">
        <a href="${data.appBaseUrl}/alerts" style="display: inline-block; background: #111827; color: #FFFFFF; font-size: 13px; font-weight: 700; padding: 12px 28px; border-radius: 50px; text-decoration: none;">
          Open Alert Command Center →
        </a>
      </div>
    </div>
  </div>
</body>
</html>`.trim();

  const text = `Fleet Alert Digest\n${alerts.length} Active Alerts\n\n${alerts.map((a) => `- [${a.type}] ${a.title}`).join("\n")}\n\nOpen Alerts: ${data.appBaseUrl}/alerts`;

  return { subject, html, text };
}
